version: 2

sources:
  - name: raw
    database: lakehouse
    schema: dbo
    tables:
      - name: customers
        identifier: raw_customers
      - name: payments
        identifier: raw_payments
      - name: orders
        identifier: raw_orders
