fabric_demo:
  target: dev
  outputs:
    dev:
      type: fabric
      driver: "ODBC Driver 17 for SQL Server" # (The ODBC Driver installed on your system)
      server: frwcevmdbmqunjon5dqok7wjea-2f4tch7i73yuvfnbx4al4duyhy.datawarehouse.fabric.microsoft.com
      port: 1433
      database: warehouse
      schema: fabric_demo
      authentication: CLI
